FROM adoptopenjdk/openjdk16:ubi
MAINTAINER ostrowski.opalka
COPY target/skiecommenrce-backed-0.0.1-SNAPSHOT.jar skiecommenrce-backed-0.0.1-SNAPSHOT.jar
EXPOSE 8090
ENTRYPOINT ["java","-jar","/skiecommenrce-backed-0.0.1-SNAPSHOT.jar"]